export const myProjects = [
  {
    id: 1,
    name: "Criativo",
    category: "css",
    img: "./criativo.png",
    desc: "Criativo is a creative platform showcasing design services, featuring a professional and user-friendly interface. Built with HTML and CSS, the site offers a responsive design, ensuring smooth performance across all devices.",
    github: "https://github.com/OnarAstro/Criativo",
    live: "https://onarastro.github.io/Criativo/",
  },
  {
    id: 2,
    name: "Deliver",
    category: "css",
    img: "./del.png",
    desc: "Deliver is a web platform for managing delivery services, featuring a simple design and an attractive, user-friendly interface. Built with HTML and CSS, it offers a responsive layout that ensures efficiency across various devices.",
    github: "https://github.com/OnarAstro/Deliver",
    live: "https://onarastro.github.io/Deliver/",
  },
  {
    id: 3,
    name: "Food",
    category: "react",
    img: "./Food.png",
    desc: "Food is a web platform designed to showcase food and meal services. It features a simple and attractive interface that allows users to easily browse the menu, select their favorite dishes, and add them to their cart. The site is built with React, offering a dynamic and responsive design that ensures seamless performance across all devices.",
    github: "https://github.com/OnarAstro/Food",
    live: "https://food-ee848.web.app/",
  },
  {
    id: 4,
    name: "E-commerce Full",
    category: "Node",
    img: "./ecom-full.png",
    desc: "A fully responsive e-commerce platform built using React.js and Node.js, delivering a seamless shopping experience through a modern and intuitive user interface. Features include product management, a dynamic shopping cart, secure user authentication, and compatibility across all devices.",
    github: "https://github.com/OnarAstro/ecom-front",
    live: "https://ecom-astro1.web.app/",
  },
  {
    id: 5,
    name: "Portfolio",
    category: "react",
    img: "./pro.png",
    desc: "React Portfolio is a personal website showcasing your skills, projects, and experience. It features a modern design and smooth user interface, with a responsive experience across all devices, built using React",
    github: "https://github.com/OnarAstro/portfoloi",
    live: "https://react-portfolio-57e83.web.app/",
  },
  {
    id: 6,
    name: "E-commerce",
    category: "react",
    img: "./Cover.png",
    desc: "E-commerce is a web platform for online shopping, allowing users to browse products, add them to the cart, and complete purchases. It features a modern, user-friendly design with an interactive, responsive interface that works seamlessly across all devices. Built with React and Firebase, the site efficiently manages products and transactions, providing users with a smooth and secure shopping experience.",
    github: "https://github.com/OnarAstro/app-ecommerce",
    live: "https://ecommerce-e3f4d.web.app/",
  },
  {
    id: 7,
    name: "Insta-clone",
    category: "fullstack",
    img: "./insta.png",
    desc: "Insta Clone is a replica of the Instagram app developed using React. It allows users to interact with posts, upload images, and follow accounts. The site features a design similar to the original Instagram app with an interactive, responsive user interface that works smoothly across all devices. It utilizes modern technologies like React and Firebase for efficient data management and operations.",
    github: "https://github.com/OnarAstro/insta-clone",
    live: "https://github.com/OnarAstro/insta-clone",
  },
  {
    id: 8,
    name: "E-commerce Full",
    category: "fullstack",
    img: "./ecom-full.png",
    desc: "A fully responsive e-commerce platform built using React.js and Node.js, delivering a seamless shopping experience through a modern and intuitive user interface. Features include product management, a dynamic shopping cart, secure user authentication, and compatibility across all devices.",
    github: "https://github.com/OnarAstro/ecom-front",
    live: "https://ecom-astro1.web.app/",
  },
  {
    id: 9,
    name: "E-commerce Admin Dashboard",
    category: "Node",
    img: "./Admin-panel.png",
    desc: "E-commerce Admin Dashboard is a management platform for an online store, enabling administrators to efficiently manage products, orders, and users. It features a clean and organized design with an interactive interface for seamless operations. Built with React and Firebase, it ensures high performance and effective data management, with a responsive design suitable for all devices.",
    github: "https://github.com/OnarAstro/ecom-node",
    live: "https://ecom-admin-8f4ad.web.app/",
  },
  {
    id: 10,
    name: "E-commerce Admin Dashboard",
    category: "fullstack",
    img: "./Admin-panel.png",
    desc: "E-commerce Admin Dashboard is a management platform for an online store, enabling administrators to efficiently manage products, orders, and users. It features a clean and organized design with an interactive interface for seamless operations. Built with React and Firebase, it ensures high performance and effective data management, with a responsive design suitable for all devices.",
    github: "https://github.com/OnarAstro/ecom-node",
    live: "https://ecom-admin-8f4ad.web.app/",
  },

];